version: "3.9"

networks:
  elastic: { }

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    networks:
      - elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - log_volume:/usr/share/elasticsearch/data
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.3
    networks:
      - elastic
    ports:
      - "5601:5601"
    volumes:
      - kibana_volume:/usr/share/kibana/data
    environment:
      ELASTICSEARCH_HOSTS: '["https://elastic:9200"]'
      
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:1.0.5
    ports:
      - "1433:1433"
    volumes:
      - sql_volume:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: MyP@ssword

volumes:
  log_volume: { }
  kibana_volume: { }
  sql_volume: { }
