version: "3.9"

networks:
  elastic: { }

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    networks:
      - elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - log_volume:/usr/share/elasticsearch/data
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.3
    networks:
      - elastic
    ports:
      - "5601:5601"
    volumes:
      - kibana_volume:/usr/share/kibana/data
    environment:
      ELASTICSEARCH_HOSTS: '["https://elastic:9200"]'

volumes:
  log_volume: { }
  kibana_volume: { }
